### ISSUE TITLE
Missing dependancy

### ISSUE THREAD

**Issue by TheRealJP** [chadalen/astraeus-client#2]
Currently missing the apache commons compress library.
Could you perhaps add it to the repository or convert the project to maven or gradle?

**Comment by IanWONeill** [comment]
https://commons.apache.org/proper/commons-compress/download_compress.cgi

**Comment by TheRealJP** [comment]
Thanks @IanWONeill, but I think it would be more convenient for other contributors if the dependencies were included in the build via maven or gradle.

**Comment by chadalen** [comment]
@TheRealJP I'm open to converting the project into a Gradle project.
