### ISSUE TITLE
Packing Widgets

### ISSUE THREAD

**Issue by IanWONeill** [chadalen/astraeus-client#4]
Instead of packing widgets into the _main_file_sprites.dat_ is there not a way to dump all the Widgets from the real 474 cache and repack them into the 317 cache?

https://www.rune-server.ee/runescape-development/rs2-client/tools/323255-custom-sprite-cache.html
https://www.rune-server.ee/runescape-development/rs2-client/snippets/583196-packing-interfaces-galkons-tool.html

Also would _main_file_sprites.dat_ work with **_JAGGRAB_**? Could we not pack the cache with the sprites, and allow it work with _**JAGGRAB**_ also? What are your thaughts on the issue?

**Comment by TheRealJP** [comment]
This is a 317 client, what benefits arise from adding 474 data?
